### ISSUE TITLE
basic auth user don't work

### ISSUE THREAD

**Issue by cryptolukas** [prometheus-community/ansible#161]
Hi I tried to used the config as mentioned and on the remote system with the right package. I get the following error from ansible.

```
- hosts: public
  pre_tasks:
    - name: Install passlib python package
      ansible.builtin.pip:
        name: passlib[bcrypt]
    - name: Create node_exporter cert dir
      file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root
    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      community.crypto.openssl_privatekey:
        path: /etc/node_exporter/tls.key
    - name: Generate an OpenSSL Certificate Signing Request
      community.crypto.openssl_csr:
        path: /etc/node_exporter/tls.csr
        privatekey_path: /etc/node_exporter/tls.key
        common_name: "{{ ansible_hostname}}"
    - name: Create cert and key
      community.crypto.x509_certificate:
        path: /etc/node_exporter/tls.cert
        csr_path: /etc/node_exporter/tls.csr
        privatekey_path: /etc/node_exporter/tls.key
        provider: selfsigned
  roles:
    - prometheus.prometheus.node_exporter
  vars:
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
    node_exporter_basic_auth_users:
      export_user: "OOkxA0L1M7KLPgwedwedW9DPL8I0XwvAq65oI"
```

```
The full traceback is:
Traceback (most recent call last):
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/plugins/action/template.py", line 139, in run
    resultant = self._templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/template/__init__.py", line 1066, in do_template
    res = j2_concat(rf)
          ^^^^^^^^^^^^^
  File "<template>", line 88, in root
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/template/__init__.py", line 264, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/plugins/filter/core.py", line 273, in get_encrypted_password
    return passlib_or_crypt(password, hashtype, salt=salt, salt_size=salt_size, rounds=rounds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/utils/encrypt.py", line 203, in passlib_or_crypt
    return CryptHash(algorithm).hash(secret, salt=salt, salt_size=salt_size, rounds=rounds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/utils/encrypt.py", line 100, in hash
    return self._hash(secret, salt, rounds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/pipx/venvs/ansible-base/lib/python3.11/site-packages/ansible/utils/encrypt.py", line 119, in _hash
    result = crypt.crypt(secret, saltstring)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/crypt.py", line 86, in crypt
    return _crypt.crypt(word, salt)
           ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
fatal: [ares.mldsc.de]: FAILED! => {
    "changed": false,
    "msg": "OSError: [Errno 22] Invalid argument"
}
```

Just to be sure. the password are hashed on the remote system right?

**Comment by cryptolukas** [comment]
Can someone help me?

**Comment by gifff** [comment]
> Just to be sure. the password are hashed on the remote system right?

I tried installing the `passlib` Python package on the controller node and it works.

**Comment by ansonhoyt** [comment]
It looks like you have a pre_task to install `passlib` on the *remote* host, but don't you want it on the *controller* as @gifff mentioned?

**Comment by cryptolukas** [comment]
Found the issue. If you use pipx here comes the magic.
```
pipx inject ansible-base passlib
```
