### ISSUE TITLE
node_exporter install could not find or access /tmp/node_exporter

### ISSUE THREAD

**Issue by laurent-indermuehle** [prometheus-community/ansible#284]
With 0.11.3 and node_exporter  1.7.0 I can't get the role to install the binary on target nodes.

I always got this error. I had to unpack manually to get past the "Unpack node_exporter binary" tasks. But after that, even if the files are at the correct location, ansible complains with : `Could not find or access '/tmp/node_exporter-1.7.0.linux-amd64/node_exporter' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option`

Here is the complete output:

```
TASK [prometheus.prometheus.node_exporter : Unpack node_exporter binary] **************************************************************************************************************************************************************
task path: /usr/share/ansible/collections/ansible_collections/prometheus/prometheus/roles/node_exporter/tasks/install.yml:40
Read vars_file '../vaults/{{ env }}.yml'
Read vars_file '../group_vars/{{ env }}/epfl_os_base.yml'
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/72dc686b8e"' localhost '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<localhost> (0, b'/root\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/72dc686b8e"' localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1706802840.3089702-110-143054497057113 `" && echo ansible-tmp-1706802840.3089702-110-143054497057113="` echo /root/.ansible/tmp/ansible-tmp-1706802840.3089702-110-143054497057113 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1706802840.3089702-110-143054497057113=/root/.ansible/tmp/ansible-tmp-1706802840.3089702-110-143054497057113\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/72dc686b8e"' -tt localhost '/bin/sh -c '"'"'test -e /tmp/node_exporter-1.7.0.linux-amd64/node_exporter && sleep 0'"'"''
<localhost> (1, b'', b'Shared connection to localhost closed.\r\n')
<localhost> Failed to connect to the host via ssh: Shared connection to localhost closed.
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/72dc686b8e"' localhost '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1706802840.3089702-110-143054497057113/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible/plugins/action/unarchive.py", line 73, in run
    source = self._loader.get_real_file(self._find_needle('files', source), decrypt=decrypt)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py", line 1455, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python3.9/site-packages/ansible/parsing/dataloader.py", line 341, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])
ansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/node_exporter-1.7.0.linux-amd64.tar.gz' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [aap_control_p2 -> localhost]: FAILED! => {
    "changed": false,
    "msg": "Could not find or access '/tmp/node_exporter-1.7.0.linux-amd64.tar.gz' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}
```

My playbook target the root user.

Here is the content of the /tmp folder after the `Download node_exporter binary to local folder` tasks:

```
# ls -alZ /tmp
total 10224
drwxrwxrwt. 17 root root system_u:object_r:tmp_t:s0                       4096 Feb  1 16:55 .
dr-xr-xr-x. 18 root root system_u:object_r:root_t:s0                       235 Dec 14 11:34 ..
-rw-r--r--.  1 root root unconfined_u:object_r:admin_home_t:s0        10419253 Feb  1 16:52 node_exporter-1.7.0.linux-amd64.tar.gz
```
I tried to disable SeLinux, with no_luck.

I've done an `tar xf` and then scp the binary on all nodes in /usr/local/bin and now the role works.
Is there a problem with those 2 tasks?
- Unpack node_exporter binary
- Propagate node_exporter binaries

**Comment by gardar** [comment]
What does your playbook look like?

**Comment by laurent-indermuehle** [comment]
Right @gardar, I forgot to join the playbook used:

```yaml
---
- name: Playbook to prepare the OS
  hosts:
    - automationcontroller
    - automationhub
    - automationedacontroller
    - database
  gather_facts: true
  vars:
    ansible_user: root
  vars_files:
    - ../vaults/{{ env }}.yml
    - ../group_vars/{{ env }}/os_base.yml
  tasks:

    - name: Import Prometheus node_exporter role
      ansible.builtin.import_role:
        name: prometheus.prometheus.node_exporter
...
```

**Comment by gardar** [comment]
Ok that playbook looks fine, looking at the debug output it looks like it's trying to ssh to localhost 😕 
Is localhost in your inventory? AFAIK it shouldn't be in the inventory, but I'd be interested to know if defining it in the inventory like this: `localhost ansible_connection=local` would make any difference.

**Comment by laurent-indermuehle** [comment]
Hi @gardar, your comment helped me find the issue!  I'm using ansible-navigator with an execution environment (EE).
So the `/tmp` from the log refer to the path inside the EE.

To fix the issue, I had to mount `/tmp` from my workstation inside the EE. Here is how it's done in `ansible-navigator.yml`:
```yml
  execution-environment:
    volume-mounts:
      - src: "/tmp"
        dest: "/tmp"
```

Now everything works!
I hope every exporter's role use the same path. I don't think the roles offer a way to choose a path. So maybe it's an opportunity to enhance the documentation for ansible-navigator users?
